//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTL.Infrastructure.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTable
    {
        public int Id { get; set; }
        public int TodoId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Reminder { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual TodoTable TodoTable { get; set; }
    }
}
